### ISSUE TITLE
What does 3x network redundancy mean?

### ISSUE THREAD

**Issue by milindpatel63** [hekmon/btfsautohostprice#1]
I wanna clarify the formula you are using to calculate the price.
What does 10usd denote? Is it the amount i want to earn every month? If so, then for how much data do you take into mind?

What does 3x network redundancy denote?

If i am allocating a space of 200GB, what should i set the terabytemonthusd value to?

**Comment by hekmon** [comment]
It was my understanding that if a user want to store 1TB of data, he will in fact consumes 3TB on the network because of the 3x replica factor (which is part of the network design principles if I remember correctly, but I can not find where I read that back then).

10usd is totally arbitrary, I based that price on my own limit: I personnaly would not pay 1TB more than 10USD per month.

So the idea is simple: if a user want to store 1TB at a reasonnable price (10$) he will consume 3TB on the network. If my node host 1TB of these 3TB I need to set my node price to: `convertUSDtoBTT(10/3)`

I might be wrong, but by the time I played with BTFS, this was my current undestanding :)

**Comment by milindpatel63** [comment]
Ok, thanks,,,got your concept..
But, according to btfs documentation... https://docs.btfs.io/docs/what-is-btfs#pricing-structure-beta

Renter Pays
3,840 BTT/TB/Month

Host Earns (BTT)
3,840 BTT/TB/Month

*Note: Renter uploading 1 TiB of data will actually generate 3 TiB of storage. BTFS pricing structure above is in the beta stage, and subject to change. More advanced pricing structures to be introduced in the near future.

So its very confusing...
On one side, they are saying that 1TB of data will generate 3TB on network...
But then they mention that user whatever the renter pays, the host will get the same amount...
SHouldn't the host get 1/3rd of the amount paid by the renter, since the same file is given to total of 3 hosts for duplication...

**Comment by hekmon** [comment]
> SHouldn't the host get 1/3rd of the amount paid by the renter, since the same file is given to total of 3 hosts for duplication...

That was my understanding, there for I divided my host price by 3: better be cheaper than too expansive in order to get contracts (there is a lot of hosts and not so many contracts out there...) ¯\\_(ツ)_/¯
